name: Windows RDP Machine

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP Port
      run: |
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set RDP User
      run: |
        net user admin123 Pass@1234 /add
        net localgroup administrators admin123 /add

    - name: Show Public IP
      run: |
        Invoke-RestMethod -Uri "https://api.ipify.org?format=json"
